# Generated by Django 4.0.6 on 2022-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_products_options_alter_wanted_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='image',
            field=models.ImageField(default='/blesseddefault.jpeg', upload_to=''),
        ),
    ]
